descriptor-schema-version: "2.2"
info:
  name: devhub-docker.cisco.com/iox-docker/ir800/base-rootfs
  version: latest
app:
  cpuarch: x86_64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    cpu: 50
    disk: 2
    memory: 64
    network:
    - interface-name: eth0
      ports: {}
    devices:
    - device-id: /dev/ttyS1
      label: async0
      type: serial
    profile: custom
  startup:
    rootfs: rootfs.tar
    target:
    - /bin/sh
  type: docker
